### PR TITLE
Add support for HikariCP

### PR DESCRIPTION
**Pull request by lukashinsch**
This PR adds support for HikariCP which is the default in spring boot 2.x.

### CODE REVIEW

**Comment by lukashinsch** [comment]
Not sure about the tests, couldn't get them to succeed locally even without the changes...

**Comment by lukashinsch** [comment]
Hi @sylvainlaurent, any interest in this? Or is this (great and useful) tool no longer maintained?

**Comment by sylvainlaurent** [comment]
hello,

thanks @lukashinsch for your contribution. I still maintain this project but not very actively as I no longer use it very often...
Your PR seems to be fine, I would just like it to contain some tests..
you say that the tests do not work on master branch currently? what's the problem?

**Comment by lukashinsch** [comment]
yeah, I couldn't get the tests to run locally from master, don't remember what the issue was need to take another look when I got a minute

**Comment by sylvainlaurent** [comment]
I removed specific-support for spring-boot as SB2 does not allow to apply a Bean post processor on the datasource. The logger still works, but you have to prepend the JDBC url with `jdbcperflogger:` and possibly set the driver class name to `ch.sla.jdbcperflogger.driver.WrappingDriver`

**Pull request closed without merging**
